<?php
//CMS создана разработчиком Ruslaan1!
$config = array (
  'main' => 
  array (
    'installed' => true,
    'site_name' => 'SMM',
    'db_host' => 'localhost',
    'db_name' => 'u1380382_default',
    'db_user' => 'u1380382_default',
    'db_pass' => 'gXGitED9h1wpG8d9',
    'db_port' => '3306',
    'mainurl' => 'socialmanedger.ru/',
    'telephone' => 'none',
    'vk' => 'none',
    'text' => 'testt',
  ),
  'social' => 
  array (
    1 => 
    array (
      'name' => 'INSTAGRAM',
      'imgone' => '/images/uslugi1.png',
      'imgtwo' => '/images/icon1.png',
      'text' => '<p>INSTAGRAM</p>
',
      'aray' => 
      array (
        1 => 
        array (
          'name' => 'подписчиков',
          'nametwo' => 'Подписчики',
          'cost' => '10',
          'costfor' => '1',
        ),
        2 => 
        array (
          'name' => 'лайки',
          'nametwo' => 'Лайки',
          'cost' => '10',
          'costfor' => '1',
        ),
      ),
    ),
  ),
  'merchant' => 
  array (
    'ik_enable' => false,
    'ik_shop_id' => '',
    'ik_secret_key' => '',
    'ik_testing' => false,
    'ik_testing_key' => '',
    'up_enable' => false,
    'up_shop_id' => '',
    'up_secret_key' => '',
    'fk_enable' => true,
    'fk_shop_id' => '319345',
    'fk_shop_key_1' => '11fpn2pb',
    'fk_shop_key_2' => '11fpn2pb',
    'rk_enable' => false,
    'rk_shop_id' => '',
    'rk_shop_key_1' => '',
    'rk_shop_key_2' => '',
    'mk_enable' => false,
    'mk_shop_id' => '',
    'mk_shop_key_1' => '',
    'mk_shop_key_2' => '',
    'qiwi_enable' => false,
    'qiwikey_public' => '',
    'qiwikey_secret' => '',
    'anypay_enable' => true,
    'ap_secret_key' => '',
    'ap_project_id' => '',
    'wm_enable' => false,
    'wm_purse' => '',
    'wm_secret_key' => '',
    'wmi_enable' => false,
    'wmi_shop_id' => '',
    'wmi_secret_key' => '',
    'yomoney_enable' => true,
    'yomoney_nomer' => '123',
    'yomoney_secretkey' => '123',
    'paypal_enable' => false,
    'paypal_testing' => false,
    'paypal_user' => '',
    'paypal_password' => '',
    'paypal_signature' => '',
    'paypal_currency_code' => 'USD',
    'g2a_enable' => false,
    'g2a_hash' => '',
    'g2a_secret' => '',
    'g2a_email' => '',
    'fondy_enable' => false,
    'fondy_id' => '',
    'fondy_signature' => '',
    'fondy_credit_key' => '',
    'fondy_currency' => 'USD',
    '2check_enable' => false,
    '2check_id' => '',
    '2check_secret_word' => '',
    '2check_currency' => 'USD',
    'paysera_enable' => false,
    'paysera_currency' => 'EUR',
    'paysera_country' => 'LT',
    'paysera_projectid' => '',
    'paysera_sign_password' => '',
  ),
);
?>